version: '3'
services:
  #whispering:
  #  image: 0001coder/whispering:latest
  #  pull_policy: always
  #  ports:
  #    - "8000:8000"
  #  restart: always
  whispering-web:
    image: whispering-web:4.0
    env_file:
      - .env
    ports:
      - "8080:3000"
    restart: always
