version: '3'
services:
  whispering:
    image: 0001coder/whispering:latest
    pull_policy: always
    ports:
      - "8000:8000"
    restart: always
  whispering-web:
    image: 0001coder/whispering-web:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
